### ISSUE TITLE
/f/ tables distended

### ISSUE THREAD

**Issue by DeckardEdward** [nebukazar/OneeChan#82]
People using long names or posting files with long filenames are causing the tables to distend behind the sidebar, making the reply links unclickable.

I'm looking for a workaround in the Oneechan options, but I feel like the tables should distend vertically instead of horizontally, that way the reply links can't be pushed behind the sidebar in the first place.

**Comment by nebukazar** [comment]
What's your screen resolution?

If you put this in the custom CSS, does it still happen:

```css
.flashListing td {
  padding-left: 0 !important;
  padding-right: 0 !important!
}
```
