### ISSUE TITLE
Sidebar overlaps posts when untruncated filenames are enabled (big filenames)

### ISSUE THREAD

**Issue by lc-guy** [nebukazar/OneeChan#90]

**Comment by nebukazar** [comment]
Put this in your 4chan X custom CSS:

```css
.file-info { 
word-wrap: break-word;
}

.inline {
display:block;
}
```

Tell me if this breaks anything. I don't have access to the code atm but I'll put it in a fix soon.
