### ISSUE TITLE
Posts quoting (You) are not highlighted

### ISSUE THREAD

**Issue by nebukazar** [nebukazar/OneeChan#92]
Catalog.css:

```css
:root.highlight-you .qmark-you {
  color: rgba(" + $SS.theme.quotesYouHLColor.rgb + ",1.0);
  font-weight: bold;
}
```
Futhermore the class `.highlight-you` was already in use in:

```css
/* Posts Quoting You */
:root.highlight-you .quotesYou.opContainer,
:root.highlight-you .quotesYou > .reply {
  border-left: " + $SS.conf["Width Decoration"] + "px solid rgba(" + $SS.theme.quotesYouHLColor.rgb + ",1.0) !important;
}
:root.highlight-you .quotesYou > .sideArrows {
  color: rgba(" + $SS.theme.quotesYouHLColor.rgb + ",1.0) !important;
}
/* Your Posts */
:root.highlight-own .yourPost.opContainer,
:root.highlight-own .yourPost > .reply {
  border-left: " + $SS.conf["Width Decoration"] + "px dashed rgba(" + $SS.theme.ownPostHLColor.rgb + ",1.0) !important;
}
:root.highlight-own .yourPost > .sideArrows {
  color: rgba(" + $SS.theme.ownPostHLColor.rgb + ",1.0) !important;
}
```
